### ISSUE TITLE
Currently difficult to discern where links point to

### ISSUE THREAD

**Issue by riverar** [skiff-org/skiff-windows-app#10]
It's currently difficult to see where a link goes with `WebView2.CoreWebView2.Settings.IsStatusBarEnabled` set to `false`.

**Comment by amilich** [comment]
Good point. Maybe we should have a built-in warning redirect modal or an option for it. We had discussed this I believe.

**Comment by riverar** [comment]
@amilich Oh that's an even better idea, to avoid html/js/css in mail from spoofing the built-in status bar.

**Comment by Novack** [comment]
Oh lordy, I also miss having the preview of where the link points to, I feel kinda blindfolded. 

Im ok with the idea of an optional redirection warning, but I'd like having the status bar as usual, because is just intuitive to look for the link information in the dynamic status bar (as the standard modern browser approach). This is also the de facto way on other desktop apps like _Kiwi for Gmail_ and _Gmail Desktop_.

**Comment by Novack** [comment]
A bit of context of what we are talking about:
![image](https://github.com/skiff-org/skiff-windows-app/assets/1981463/28f83194-3a33-47b9-8fc3-b14dfa811970)

![image](https://github.com/skiff-org/skiff-windows-app/assets/1981463/f9501a0d-46d0-4506-afb9-1a30d88d551d)
_(pointer is not visible on the screenshot, but is on top of the 'open inbox' button)_

@amilich what do you think?

**Comment by amilich** [comment]
I'm fine with that!
